name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.PAT }}
        file: target/release/artifact-opener
        asset_name: artifact-opener-windows
        tag: ${{ github.ref }}
        overwrite: true

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.PAT }}
        file: target/release/artifact-opener
        asset_name: artifact-opener-macos
        tag: ${{ github.ref }}
        overwrite: true
    
          